"""File rel_path, name

Revision ID: e5bbecec4ed5
Revises: 0389adc26cce
Create Date: 2018-11-11 16:59:11.032366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bbecec4ed5'
down_revision = '0389adc26cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('file', sa.Column('rel_path', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'rel_path')
    op.drop_column('file', 'name')
    # ### end Alembic commands ###
